// Environment file generation utilities

import { getRpcPort, getPoolConfig, DEFAULT_AUTHORITY_PUBLIC_KEY, DEFAULT_CONFIG_VALUES } from '../../config-templates';

/**
 * Generate .env file content for full-stack JD deployment
 */
export const generateEnvFile = (data: any, socketPath: string): string => {
  const network = (data?.selectedNetwork || "mainnet") as 'mainnet' | 'testnet4' | 'signet';
  const coreRpcPort = getRpcPort(network);
  
  return `# Stratum V2 Full Stack Deployment Environment Variables
# Generated by SRI Deployment Wizard
# Place this file in sv2-apps/docker/.env

# Pool Configuration
POOL_COINBASE_REWARD_SCRIPT=${data?.poolPayoutAddress || 'bc1q...'}
POOL_SIGNATURE=${data?.poolSignature || 'Stratum V2 SRI Pool'}
POOL_SHARE_BATCH_SIZE=${data?.shareBatchSize || 10}
POOL_SHARES_PER_MINUTE=${data?.sharesPerMinute || 6.0}
POOL_FEE_THRESHOLD=${data?.feeThreshold || 100}
POOL_MIN_INTERVAL=${data?.minInterval || 5}

# JD Server Configuration
JDS_COINBASE_REWARD_SCRIPT=${data?.poolPayoutAddress || 'bc1q...'}
JDS_CORE_RPC_PORT=${coreRpcPort}
JDS_CORE_RPC_USER=${data?.coreRpcUser || 'username'}
JDS_CORE_RPC_PASS=${data?.coreRpcPass || 'password'}

# JD Client Configuration
JDC_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
JDC_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
JDC_SHARE_BATCH_SIZE=${data?.clientShareBatchSize || 10}
JDC_SIGNATURE=${data?.jdcSignature || 'Sv2MinerSignature'}
JDC_COINBASE_REWARD_SCRIPT=${data?.coinbaseRewardScript || 'bc1q...'}
JDC_FEE_THRESHOLD=${data?.clientFeeThreshold || 100}
JDC_MIN_INTERVAL=${data?.clientMinInterval || 5}

# Translator Proxy Configuration
TPROXY_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
TPROXY_AGGREGATE_CHANNELS=false
TPROXY_MIN_INDIVIDUAL_MINER_HASHRATE=10000000000000.0
TPROXY_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
TPROXY_UPSTREAM_ADDRESS=127.0.0.1
TPROXY_UPSTREAM_PORT=${data?.constructTemplates !== false ? DEFAULT_CONFIG_VALUES.jdcPort : DEFAULT_CONFIG_VALUES.poolPort}
TPROXY_UPSTREAM_AUTHORITY_PUBKEY=${DEFAULT_AUTHORITY_PUBLIC_KEY}

# Bitcoin Socket Path
BITCOIN_SOCKET_PATH=${socketPath}
`;
};

/**
 * Generate .env file content for pool connection deployment
 */
export const generatePoolConnectionEnvFile = (data: any, socketPath?: string): string => {
  const needsSocketPath = !!socketPath;
  const selectedPoolConfig = getPoolConfig(data?.selectedPool);
  
  let envContent = `# Stratum V2 Pool Connection Environment Variables
# Generated by SRI Deployment Wizard
# Place this file in sv2-apps/docker/.env

# Translator Proxy Configuration
TPROXY_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
TPROXY_AGGREGATE_CHANNELS=${selectedPoolConfig?.aggregateChannels ? 'true' : 'false'}
TPROXY_MIN_INDIVIDUAL_MINER_HASHRATE=10000000000000.0
TPROXY_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
TPROXY_UPSTREAM_ADDRESS=${needsSocketPath ? '127.0.0.1' : (selectedPoolConfig?.address || '127.0.0.1')}
TPROXY_UPSTREAM_PORT=${needsSocketPath ? DEFAULT_CONFIG_VALUES.jdcPort : (selectedPoolConfig?.port || DEFAULT_CONFIG_VALUES.poolPort)}
TPROXY_UPSTREAM_AUTHORITY_PUBKEY=${needsSocketPath ? DEFAULT_AUTHORITY_PUBLIC_KEY : (selectedPoolConfig?.authorityPubkey || DEFAULT_AUTHORITY_PUBLIC_KEY)}
`;

  if (needsSocketPath) {
    envContent += `
# JD Client Configuration (for custom templates)
JDC_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
JDC_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
JDC_SHARE_BATCH_SIZE=${data?.clientShareBatchSize || 10}
JDC_SIGNATURE=${data?.jdcSignature || 'Sv2MinerSignature'}
JDC_COINBASE_REWARD_SCRIPT=${data?.coinbaseRewardScript || 'bc1q...'}
JDC_FEE_THRESHOLD=${data?.clientFeeThreshold || 100}
JDC_MIN_INTERVAL=${data?.clientMinInterval || 5}

# Bitcoin Socket Path
BITCOIN_SOCKET_PATH=${socketPath}
`;
  }
  
  return envContent;
};

